### ISSUE TITLE
Add inscription color to notes

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#130]
As the inscription color will be lost (see #67 and #107) in crbirding database, I would add it to the notes (opmerking). Format: `inscription color: color_name.`  e.g. `inscription color: white.` 

@EricStienen: do you agree?

**Comment by EricStienen** [comment]
I agree Damiano.

BTW I spoke to some Dutch ring readers and for the past year they have added quite some new data to the cr-birding database. We asked SOVON several times to not yet open the project, but obviously it is still possible to eneter data. We have to find a solution so that these additions are included into our new database that will be uploaded soon.

**Comment by damianooldoni** [comment]
Thanks @EricStienen , I will add the color inscription to notes. 

About the rest, it's surely very important. I copy paste it in a new issue.
