### ISSUE TITLE
Handling data added to cr-birding database

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#133]
@EricStienen noted the following (https://github.com/inbo/cr-birding/issues/130#issuecomment-648169993):
> From BTW I spoke to some Dutch ring readers and for the past year they have added quite some new data to the cr-birding database. We asked SOVON several times to not yet open the project, but obviously it is still possible to enter data. We have to find a solution so that these additions are included into our new database that will be uploaded soon.

@JeroenNienhuis: this is, indeed, something SOVON has to keep in mind.

**Comment by JeroenNienhuis** [comment]
The INBO projects are not open for public (only for the admins of those projects). The admins can only see/test the projects if the imported birds are not deleted and the concerning species are selectable. Most of the about 200 observations (since March 2017) are entered using the generic input (where you can enter everything as long as the species is selectable). I did not check, but probably the entered observations are matched to individuals because the birds are not deleted from the database.

Finding a solution to get these data in the INBO database is not needed. All uploaded observations have a record-id from the INBO database and a label "imported from file". Data entered by observers have neither. When data from is downloaded from our website the INBO observation record-id is in the file. The data already entered by observers is recognisable in the same way as the data that will be entered after the input is open. The only difference is that the create-date of some records is before the date the input is opened.
