### ISSUE TITLE
Don't use raw prefix

### ISSUE THREAD

**Issue by peterdesmet** [inbo/sovon#48]
@damianooldoni rather than using the `raw_` prefix:

https://github.com/inbo/sovon/blob/efbf1f49630ad03ae8a0a98871e86533bf8710fa/src/map_inbo_data_to_sovon.Rmd#L181-L189

Can you leave the columns as is, but add the `sovon_` prefix when mapping to the structure of the sovon database? **That makes it easier to recognize columns**. See also the (updated!) checklist recipe on how we remove the `dwc_` prefix: https://github.com/trias-project/checklist-recipe/blob/3e7491eec1437d15a2ff542163abd72796fddd52/src/dwc_mapping.Rmd#L267

**Comment by damianooldoni** [comment]
Yes, thanks for suggesting it. I will do it. 

Just a detail, about code in recipe: https://github.com/trias-project/checklist-recipe/blob/3e7491eec1437d15a2ff542163abd72796fddd52/src/dwc_mapping.Rmd#L276

Please, consider to use `str_remove()` instead of `str_replace()`. Same effect but better to understand, as common people don't consider replacing with nothing a replacement, actually :smile: 
```r
colnames(taxon) <- str_remove_all(colnames(taxon), pattern = "dwc_")
```

**Comment by damianooldoni** [comment]
All `raw` prefixes removed.
